(define (problem problem2)
    (:domain roundabout)
    
    ; problem definition for problem 2
    
    (:objects
        r1 r2 r3 r4 r5 r6 - road
        s1 s2 s3 s4 s5 s6 - section
        v1 v2 v3 v4 v5 v6 v7 v8 v9 v10 v11 v12 v13 v14 v15 v16 v17 v18 v19 v20 - car
    )
    
    (:init
        ; section connections. For this problem, there's two roundabouts
        (connected s1 s2)
        (connected s2 s3)
        (connected s3 s1)
        (connected s4 s5)
        (connected s5 s6)
        (connected s6 s4)
        (sectionfree s1)
		(sectionfree s2)
		(sectionfree s3)
        (sectionfree s4)
		(sectionfree s5)
		(sectionfree s6)
        
        ; road connections
        (before r1 s1)
        (before r3 s2)
        (after r6 s2)
        (before r5 s3)
        (before r6 s4)
        (before r4 s5)
        (after r2 s5)
        (after r5 s6)

        ; vehicle starting points
        (atstart v1 r1)
        (atstart v2 r1)
        (atstart v3 r1)
        (atstart v4 r1)
        (atstart v5 r1)
        (atstart v6 r1)
        (atstart v7 r1)
        (atstart v8 r1)
        (atstart v9 r1)
        (atstart v10 r1)
        (atstart v11 r3)
        (atstart v12 r3)
        (atstart v13 r3)
        (atstart v14 r3)
        (atstart v15 r3)
        (atstart v16 r4)
        (atstart v17 r4)
        (atstart v18 r4)
        (atstart v19 r4)
        (atstart v20 r4)
        (insystem v1)
        (insystem v2)
        (insystem v3)
        (insystem v4)
        (insystem v5)
        (insystem v6)
        (insystem v7)
        (insystem v8)
        (insystem v9)
        (insystem v10)
        (insystem v11)
        (insystem v12)
        (insystem v13)
        (insystem v14)
        (insystem v15)
        (insystem v16)
        (insystem v17)
        (insystem v18)
        (insystem v19)
        (insystem v20)

        ; vehicle exits
        (exit v1 r2)
        (exit v2 r2)
        (exit v3 r2)
        (exit v4 r2)
        (exit v5 r2)
        (exit v6 r2)
        (exit v7 r2)
        (exit v8 r2)
        (exit v9 r2)
        (exit v10 r2)
        (exit v11 r2)
        (exit v12 r2)
        (exit v13 r2)
        (exit v14 r2)
        (exit v15 r2)
        (exit v16 r2)
        (exit v17 r2)
        (exit v18 r2)
        (exit v19 r2)
        (exit v20 r2)

        ; starting speeds
        (= (speed v1) 3)
        (= (speed v2) 3)
        (= (speed v3) 3)
        (= (speed v4) 3)
        (= (speed v5) 3)
        (= (speed v6) 3)
        (= (speed v7) 3)
        (= (speed v8) 3)
        (= (speed v9) 3)
        (= (speed v10) 3)
        (= (speed v11) 2)
        (= (speed v12) 2)
        (= (speed v13) 2)
        (= (speed v14) 2)
        (= (speed v15) 2)
        (= (speed v16) 2)
        (= (speed v17) 2)
        (= (speed v18) 2)
        (= (speed v19) 2)
        (= (speed v20) 2)

        ; starting traffic
        (= (traffic r1) 10)
        (= (traffic r2) 0)
        (= (traffic r3) 5)
        (= (traffic r4) 5)
        (= (traffic r5) 0)
        (= (traffic r6) 0)

        ; road capacities
        (= (capacity r1) 10)
        (= (capacity r2) 5)
        (= (capacity r3) 5)
        (= (capacity r4) 5)
        (= (capacity r5) 2)
        (= (capacity r6) 2)

        ; road lengths
        (= (roadlength r1) 10)
        (= (roadlength r2) 10)
        (= (roadlength r3) 10)
        (= (roadlength r4) 10)
        (= (roadlength r5) 5)
        (= (roadlength r6) 5)
    )
    
    (:goal (and 
        (exited v1)
        (exited v2)
        (exited v3)
        (exited v4)
        (exited v5)
        (exited v6)
        (exited v7)
        (exited v8)
        (exited v9)
        (exited v10)
        (exited v11)
        (exited v12)
        (exited v13)
        (exited v14)
        (exited v15)
        (exited v16)
        (exited v17)
        (exited v18)
        (exited v19)
        (exited v20)))
    
    (:metric minimize (total-time))
)